# For setup run:
# mamba env create -f environment.yml     or conda
# conda activate '02466_AI_dubbing'
# python -m ipykernel install --user --name='02466_AI_dubbing' --display-name "Python ('02466_AI_dubbing')"

# Add new packages under dependencies or pip.
# To update env, run the following:
# mamba env update -f environment.yml --prune     or conda
  
name: 02466_AI_dubbing
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.10
  - pip
  - ffmpeg
  - pytorch
  - torchaudio
  - ipykernel
  - notebook
  - python-sounddevice
  - datasets
  - librosa
  - transformers
  - jiwer
  - sentencepiece
  - pip:
      - faster-whisper
      - pydub
      - silero-vad[onnx]
      - num2words
      - evaluate
      - unbabel-comet
      - pyctcdecode